name: Deploy AI DJ to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  PYTHON_VERSION: '3.12'
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      # ========================================
      # Checkout del código
      # ========================================
      - name: Checkout code
        uses: actions/checkout@v4

      # ========================================
      # Configurar credenciales de AWS
      # ========================================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ========================================
      # Configurar Node.js (requerido para CDK)
      # ========================================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # ========================================
      # Instalar AWS CDK CLI
      # ========================================
      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk@latest
          cdk --version

      # ========================================
      # Configurar Python
      # ========================================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      # ========================================
      # Instalar dependencias del proyecto CDK
      # ========================================
      - name: Install CDK dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ========================================
      # Instalar dependencias de Lambda
      # ========================================
      - name: Install Lambda dependencies
        run: |
          cd lambda_src
          pip install -r requirements.txt -t .
          cd ..

      # ========================================
      # Sintetizar el stack de CDK
      # ========================================
      - name: CDK Synth
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          cdk synth

      # ========================================
      # Bootstrap de CDK (solo primera vez)
      # ========================================
      - name: CDK Bootstrap
        run: |
          cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }} || true

      # ========================================
      # Desplegar el stack
      # ========================================
      - name: CDK Deploy
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          cdk deploy --require-approval never --outputs-file outputs.json

      # ========================================
      # Mostrar outputs del despliegue
      # ========================================
      - name: Display deployment outputs
        run: |
          echo "=== Deployment Outputs ==="
          cat outputs.json
          echo ""
          echo "API Endpoint:"
          cat outputs.json | grep -o '"ApiEndpoint": "[^"]*"' | cut -d'"' -f4 || echo "Not found"

      # ========================================
      # Subir outputs como artefacto
      # ========================================
      - name: Upload deployment outputs
        uses: actions/upload-artifact@v4
        with:
          name: deployment-outputs
          path: outputs.json
          retention-days: 30
